title: "Maggie Zhu"
author: "Maggie Zhu"
email: "maggiezhu0604@gmail.com"
description: "Plant breeding, quantitative genetics, genomic prediction, high-throughput phenotyping, and breeding decision support."

remote_theme: daattali/beautiful-jekyll@6.0.1

navbar-links:
  About: "/"
  Project: "/project"
  Outreach: "/outreach"
  Blog: "/blog"
  Contact: "/contact"

avatar: "/assets/img/profile.jpg"
round-avatar: true
site-css:
  - "/assets/css/custom-styles.css"

social-network-links:
  email: "maggiezhu0604@gmail.com"
  github: maggiezhu0604
  linkedin: maggie-dan-zhu

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false

url-pretty: "maggiezhu0604.github.io"
title-on-all-pages: true
feed_show_excerpt: true
remove-ads: true

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
