title: "Your Name"
author: "Your Name"
email: "your.email@example.com"
description: "Personal academic website in plant breeding and data science."

remote_theme: daattali/beautiful-jekyll@6.0.1

navbar-links:
  About: "about"
  Research: "research"
  Projects: "projects"
  CV: "cv"
  Contact: "contact"

avatar: "/assets/img/profile.jpg"
round-avatar: true
site-css:
  - "/assets/css/custom-styles.css"

social-network-links:
  email: "your.email@example.com"
  github: your-github
  linkedin: your-linkedin
  google-scholar: your-scholar-id

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false

url-pretty: "yourname.github.io"
title-on-all-pages: true
feed_show_excerpt: true
remove-ads: true

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
